---
- hosts: ambari
  become: yes
  become_user: root


  tasks:
   - name: Install ambari.repo
     get_url:
       dest: /etc/yum.repos.d/ambary.repo
       url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.0.0/ambari.repo 

   - name: Install openjdk/chrony.
     yum:
       name: "{{item}}"
       state: present
     with_items:
       - java-1.8.0-openjdk.x86_64
       - chrony

   - name: Set environment variable JAVA_HOME
     lineinfile:
       path: /etc/environment
       regexp: '^JAVA_HOME='
       line: 'JAVA_HOME=/etc/alternatives/jre_openjdk'

   - name: Startup chronyd service
     service: 
       name: "{{item}}"
       state: started
       enabled: yes
     with_items:
       - chronyd

   - name: Synchronize time
     command: chronyc sources -v

   - name: Stop firewalld service
     service: 
       name: "{{item}}"
       state: stopped
       enabled: no
     with_items:
       - firewalld
     when: inventory_hostname != "r4host8.deloittecloud.com"
      
   - name: Make directory /opt/hadoop on hosts except r4host8.deloittecloud.com.
     file: 
       path: "{{item}}"
       owner: root
       group: root
       mode: 0755
       recurse: yes
       state: directory
     with_items:
       - /opt/hadoop/hdfs/namenode
       - /opt/hadoop/hdfs/data
     when: inventory_hostname != "r4host8.deloittecloud.com"

   - name: Install Ambari agent on hosts except r4host8.deloittecloud.com.
     yum: 
       name: "{{item}}"
       state: present
     with_items:
       - ambari-agent
     when: inventory_hostname != "r4host8.deloittecloud.com"

   - name: Install expect/ambari-server on host r4host8.deloittecloud.com.
     yum:
       name: "{{item}}"
       state: present
     with_items:
       - expect
       - ambari-server
     when: inventory_hostname == "r4host8.deloittecloud.com"

   - name: Modify ambari-agent.ini
     lineinfile:
       path: /etc/ambari-agent/conf/ambari-agent.ini
       regexp: '^hostname='
       line: 'hostname=r4host8.deloittecloud.com'
     when: inventory_hostname != "r4host8.deloittecloud.com"

   - name: Setup Ambari server on host r4host8.deloittecloud.com.
     shell: |
       set timeout 10
       spawn ambari-server setup

       expect "Customize user account for ambari-server daemon \[y/n\] (n)\?"
       send "\r"

       expect "OK to continue \[y/n\] (y)?"
       send "n\r"

       expect "Enter choice (1):"
       send "3\r"

       expect "Path to JAVA_HOME:"
       send "/etc/alternatives/jre_openjdk\r"

       expect "Enter advanced database configuration \[y/n\] (n)?"
       send "\r"

       expect eof

       exit 0
     args:
       executable: /usr/bin/expect
     when: inventory_hostname == "r4host8.deloittecloud.com"
     tags:
       - ambari_server_setup

   - name: Startup ambari-server service on host r4host8.deloittecloud.com
     service: 
       name: "{{item}}"
       state: started
       enabled: yes
     with_items:
       - ambari-server
     when: inventory_hostname == "r4host8.deloittecloud.com"

   - name: Startup ambari-agent service
     service: 
       name: ambari-agent
       state: started
       enabled: yes
     when: inventory_hostname != "r4host8.deloittecloud.com"

